export const LOADING_RECIPES = 'LOADING_RECIPES';
export const LOADED_RECIPES = 'LOADED_RECIPES';
export const LOAD_RECIPES_ERROR = 'LOAD_RECIPES_ERROR';

export const LOADING_RECIPE_DETAIL = 'LOADING_RECIPE_DETAIL'
export const LOADED_RECIPE_DETAIL = 'LOADED_RECIPE_DETAIL'
export const LOADED_RECIPE_DETAIL_ERROR = 'LOADED_RECIPE_DETAIL_ERROR'

export const LOADING_DISHTYPES = 'LOADING_DISHTYPES';
export const LOADED_DISHTYPES = 'LOADED_DISHTYPES';
export const LOAD_DISHTYPES_ERROR = 'LOAD_DISHTYPES_ERROR';


export const ADDING_RECIPE = 'ADDING_RECIPE';
export const ADDED_RECIPE = 'ADDED_RECIPE';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';
